add_newline = true

[character]
success_symbol = "[❯](bold green)"
vicmd_symbol = "[❮](bold green)"
error_symbol = "[X](bold red)"

[directory]
truncation_length = 2
truncate_to_repo = false
style = "bold blue"
format = "[$path]($style)[$read_only]($read_only_style) "

[dotnet]
symbol = "[.NET] "
style = "dimmed blue"
heuristic = true
  
[rust]
symbol = "[Rust] "
style = "dimmed red"

[nodejs]
symbol = "[NodeJS] "
style = "dimmed green"

[java]
symbol = "[Java] "
style = "dimmed purple"

[git_branch]
symbol = " "
style = "bold green"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
conflicted = "  "
deleted = " 﫧"
modified = "  "
stashed = "  "
staged = "  "
renamed = "  "
untracked = "  "

[package]
disabled = false
symbol = ""
style = "bold white"

[time]
disabled = false
format = '[$time]($style) '
time_format = "%T"